# Gradle runtime
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Project identity
mod_id=ravensmodels
mod_name=Raven's Models
maven_group=io.github.recrivenvi
artifact_name=ravensmodels
mod_author=RavenYin
mod_homepage=https://github.com/RecRivenVI/RavensMod
mod_sources=https://github.com/RecRivenVI/RavensMod

# Release identity
mod_version=1.0.0
