# Gradle runtime
org.gradle.jvmargs=-Xmx1G -Dhttps.protocols=TLSv1.2,TLSv1.3 -Djdk.tls.client.protocols=TLSv1.2,TLSv1.3
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Project identity
mod_id=ravensmod
mod_name=Raven's Mod
maven_group=io.github.recrivenvi
artifact_name=ravensmod
mod_author=RavenYin
mod_description=A mod programmed by RavenYin, specially made for RadianceMod
mod_homepage=https://github.com/RecRivenVI/RavensMod
mod_sources=https://github.com/RecRivenVI/RavensMod

# Release identity
mod_version=1.0.0
