# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G -Dhttps.protocols=TLSv1.2,TLSv1.3 -Djdk.tls.client.protocols=TLSv1.2,TLSv1.3
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod Properties
mod_id=ravensmod
mod_name=Raven's Mod
mod_version=1.0.0
mod_group=com.recrivenvi.ravensmod

# Fabric Loom
deps.loom=1.17.11
