name: build
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: upload 1.21.4
        uses: actions/upload-artifact@v5
        with:
          name: ravensmod-1.21.4
          path: versions/1.21.4/build/libs/*.jar
          compression-level: 0
      - name: upload 26.1.2
        uses: actions/upload-artifact@v5
        with:
          name: ravensmod-26.1.2
          path: versions/26.1.2/build/libs/*.jar
          compression-level: 0
